### PR TITLE
Where is class StatelessWidget?

### PR DESCRIPTION
**Pull request by jenny-cyc**
Where is class StatelessWidget?

### CODE REVIEW

**Comment by YJC-23** [comment]
Good question :)

**Comment by YJC-23** [comment]
good question :)

**Comment by pstringe** [comment]
StatelessWidget is a built-in class. You won't find it in the project files. It's in the flutter binaries themselves. If you are interested in learning about the inner-working of the framework you can check out their git repo: https://github.com/flutter/flutter.git

**Comment by YuraT** [comment]
removing old stuff

**Pull request closed without merging**
